scrapy crawl cntvspider -a keyword=嫖娼 -a topictitle=嫖娼
scrapy crawl cntvspider -a keyword=开房 -a topictitle=嫖娼
scrapy crawl cntvspider -a keyword=强奸 -a topictitle=嫖娼
scrapy crawl cntvspider -a keyword=招嫖 -a topictitle=嫖娼
scrapy crawl cntvspider -a keyword=举报 -a topictitle=反腐败
scrapy crawl cntvspider -a keyword=腐败 -a topictitle=反腐败
scrapy crawl cntvspider -a keyword=村干部 -a topictitle=反腐败
scrapy crawl cntvspider -a keyword=村官 -a topictitle=反腐败
scrapy crawl cntvspider -a keyword=官二代 -a topictitle=反腐败
scrapy crawl cntvspider -a keyword=招待费 -a topictitle=反腐败
scrapy crawl cntvspider -a keyword=纪委 -a topictitle=反腐败
scrapy crawl cntvspider -a keyword=公款吃喝 -a topictitle=反腐败
scrapy crawl cntvspider -a keyword=公车私用 -a topictitle=反腐败
scrapy crawl cntvspider -a keyword=上访 -a topictitle=反腐败
scrapy crawl cntvspider -a keyword=官员 -a topictitle=反腐败
scrapy crawl cntvspider -a keyword=贪污 -a topictitle=反腐败
scrapy crawl cntvspider -a keyword=受贿 -a topictitle=反腐败
scrapy crawl cntvspider -a keyword=静坐 -a topictitle=游行示威
scrapy crawl cntvspider -a keyword=围攻 -a topictitle=游行示威
scrapy crawl cntvspider -a keyword=游行 -a topictitle=游行示威
scrapy crawl cntvspider -a keyword=示威 -a topictitle=游行示威
scrapy crawl cntvspider -a keyword=纵火 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=批捕 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=死刑 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=刑拘 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=终审 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=一审 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=二审 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=公诉 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=警方通报 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=虐待 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=枪杀 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=殴打 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=无证驾驶 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=投毒 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=扶老人 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=超生 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=贩婴 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=城管 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=酒驾 -a topictitle=涉警涉法
scrapy crawl cntvspider -a keyword=地震 -a topictitle=自然灾害
scrapy crawl cntvspider -a keyword=洪水 -a topictitle=自然灾害
scrapy crawl cntvspider -a keyword=台风 -a topictitle=自然灾害
scrapy crawl cntvspider -a keyword=雾霾 -a topictitle=自然灾害
scrapy crawl cntvspider -a keyword=暴雪 -a topictitle=自然灾害
scrapy crawl cntvspider -a keyword=救灾物资 -a topictitle=自然灾害
scrapy crawl cntvspider -a keyword=死猪 -a topictitle=食品安全
scrapy crawl cntvspider -a keyword=奶粉 -a topictitle=食品安全
scrapy crawl cntvspider -a keyword=污染 -a topictitle=食品安全
scrapy crawl cntvspider -a keyword=幼女 -a topictitle=未成年人安全
scrapy crawl cntvspider -a keyword=幼童 -a topictitle=未成年人安全
scrapy crawl cntvspider -a keyword=婴儿 -a topictitle=未成年人安全
scrapy crawl cntvspider -a keyword=男童 -a topictitle=未成年人安全
scrapy crawl cntvspider -a keyword=女童 -a topictitle=未成年人安全
